services:
  - type: web
    name: fitzone-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fitzone-db
          property: connectionString

databases:
  - name: fitzone-db
    plan: free